variable "filename" {
    default = "/home/ubuntu/terraform/terraform-variable/devops-automated.txt"
}


variable "content" {
    default = "This is autogenerated variable"

}


variable "devops_engineer" {}


variable "file_contents" {
    type = map
    default = {
       "content1" = "This is new line 1"
       "content2"  = "This is new line 2"
}
}

variable "file_list" {
  type = list

  default = ["/home/ubuntu/terraform/terraform-variable/file1.txt","/home/ubuntu/terraform/terraform-variable/file2.txt"]

}

variable "aws_ec2_object" {
  type = object ({
       name = string
       instance = number
       keys = list(string)
       ami = string


})
default = {
    
      name = "aws_test_ec2"
      instance = 4
      keys = ["key1.pem","key2.pem"]
      ami = "ubuntu-ec2ami53980fg"



}

}
